### ISSUE TITLE
Fix the `fedora` image builds

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/ci-images#88]
The `fedora` images aren't being built successfully on the regular schedule. Looks like an issue with conflicting JDK packages:

https://github.com/insightsengineering/ci-images/actions/runs/6789540720/job/18456975869
https://github.com/insightsengineering/ci-images/actions/runs/6789540502/job/18456973758

**Comment by walkowif** [comment]
This seems to be caused by an outdated Fedora version and its repository (as described [here](https://discussion.fedoraproject.org/t/fedora-36-recent-java-update-conflicts-with-java-17/82840)).

`rhub-fedora` images are still based on [Fedora 36](https://github.com/r-hub/rhub-linux-builders/blob/master/fedora/Dockerfile#L3).

One workaround would be to remove `java-latest-openjdk-devel` and `java-latest-openjdk` from the list of installed packages so that only `java-17-openjdk-headless-1:17.0.7.0.7-1.fc36.x86_64` package is installed without conflicts.

**Comment by walkowif** [comment]
Yes, skipping the `java-latest-openjdk-devel` and `java-latest-openjdk` from package list altogether results in `java-17-openjdk-headless-1` being installed, likely as a dependency of another package from the list.
